server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka


spring:
  application:
    name: customer-service
  main:
    allow-circular-references: true
  zipkin:
    base-url: http://localhost:9411/
  mail:
    host: smtp.gmail.com
    port: 587
    username: sauravi.thapa@gmail.com
    password: aprIl082019
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


sleuth:
  sampler:
    probability: 1


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000