server:
  port: 8084

Spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sauravi.thapa96@gmail.com
    password: aprIl082019
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
