server:
  port: 8081

#MongoDb Config
spring:
  application:
    name: product-service
  main:
    allow-circular-references: true
  zipkin:
    base-url: http://localhost:9411/
sleuth:
  sampler:
    probability: 1

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000