server:
  port: 8081

#MongoDb Config
spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webstore
  zipkin:
    base-url: http://localhost:9411/
sleuth:
  sampler:
    probability: 1
