server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka


spring:
  application:
    name: Api-gateway
  cloud:
    gateway:
      routes:
        - id: productModule
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
        - id: customerModule
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: orderModule
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: shoppingCartModule
          uri: lb://SHOPPINGCART-SERVICE
          predicates:
            - Path=/shoppingCart/**
  zipkin:
    base-url: http://localhost:9411/

sleuth:
  sampler:
    probability: 1

