server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: Api-gateway
  cloud:
    gateway:
      routes:
        - id: productModule
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: customerModule
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
        - id: orderModule
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: shoppingCartModule
          uri: lb://SHOPPINGCART-SERVICE
          predicates:
            - Path=/shoppingCart/**
  zipkin:
    base-url: http://localhost:9411/

sleuth:
  sampler:
    probability: 1

